name: System Check

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  CheckOS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome"
      - name: Checking Disk Usage
      - run: df -h
      - name: Checking CPU
      - run: lscpu
      - run: cat /proc/cpuinfo
